# Generated by Django 4.2.23 on 2025-08-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
            },
        ),
        migrations.AddField(
            model_name='mesa',
            name='piso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='Pagina_Web.piso'),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('nombre', 'piso')},
        ),
    ]
