# Generated by Django 5.2.4 on 2025-08-05 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Entrada', 'Entrada'), ('Fondo', 'Plato de Fondo'), ('Postre', 'Postre'), ('Bebida', 'Bebida')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='platos/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={},
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Ocupada', 'Ocupada')], default='Libre', max_length=10),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagina_Web.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagina_Web.pedido')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagina_Web.plato')),
            ],
        ),
    ]
