# Generated by Django 5.2.4 on 2025-08-08 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Web', '0003_alter_mesa_estado_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pagina_Web.mesa')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
