# Generated by Django 5.2.4 on 2025-08-08 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Web', '0005_incidente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('numero', models.PositiveIntegerField(help_text='Número para ordenar los pisos. Ej: 1, 2, 3...', unique=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['piso__numero', 'nombre']},
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada'), ('Mantenimiento', 'Mantenimiento')], default='Libre', max_length=15),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='mesa',
            name='piso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='Pagina_Web.piso'),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('piso', 'nombre')},
        ),
    ]
