# Generated by Django 5.2.4 on 2025-08-08 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Web', '0006_piso_alter_mesa_options_alter_mesa_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='piso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='Pagina_Web.piso'),
        ),
    ]
